spring:
    profiles:
        active: 
        - dev  #表明当前启用的配置信息是开发环境的
    application:
        name: spring-cloud-config-client

eureka:
  instance:
    instance-id: config-client-001   # 当前注册实例，在 Eureka Server 中的唯一标识，配置后优化用于生成对应的超链接名称，否则使用 hostname+appname+端口号（可以理解为提供服务的实例名称）
    prefer-ip-address: true 
    
my:
  demo: "这个配置信息都会被获取到！"

---
server:
  port: 8201
spring:
    profiles: dev #开发环境
eureka:
  client: 
    service-url:
      #集群
      defaultZone: http://eureka-server-7001.com:7001/eureka/
        
---
server:
  port: 8202
spring:
    profiles: test #测试环境
eureka:
  client: 
    service-url:
      #集群
      defaultZone: http://eureka-server-7002.com:7002/eureka/
      
        
        
#注意事项：本文件需要以 UTF8 格式保存，避免微服务读取时中文乱码
#说明：
#  1. 以 --- 为分隔符，实现同一个配置文件中，定义不同的环境配置。
#  2. - 表示的是取数组中的某一个元素
#  3. 第一个未取名的配置，将视为默认配置，所有请求的配置中都会添加